version: '3'
services:
 s2:
  build: ~/github/gocode/s2
 nginx:
  image: blacklabelops/nginx
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
   - ~/keys:/opt/nginx/keys
   - ${PWD}:/var/lib/nginx/html
